-- CreateTable
CREATE TABLE "Patient" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "lastname" TEXT NOT NULL,
    "firstname" TEXT NOT NULL,
    "middlename" TEXT NOT NULL,
    "dateofbirth" TEXT NOT NULL,
    "age" INTEGER NOT NULL,
    "educationlevel" TEXT NOT NULL,
    "occupation" TEXT NOT NULL,
    "religion" TEXT NOT NULL,
    "denomination" TEXT NOT NULL,
    "photo" TEXT NOT NULL DEFAULT 'null',
    "healthinstitution" TEXT NOT NULL,
    "healthinstitutioninitials" TEXT NOT NULL,
    "clinicid" INTEGER NOT NULL DEFAULT 0,
    "patientcategory" TEXT NOT NULL,
    "maritalstatus" TEXT NOT NULL,
    "residentialaddress" TEXT NOT NULL,
    "lga" TEXT NOT NULL,
    "town" TEXT NOT NULL,
    "postalcode" TEXT NOT NULL,
    "currentstate" TEXT NOT NULL,
    "nationality" TEXT NOT NULL,
    "addressline2" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "stateoforigin" TEXT NOT NULL,
    "gender" TEXT NOT NULL,
    "mobile" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "nokfirstname" TEXT NOT NULL,
    "noklastname" TEXT NOT NULL,
    "nokrelationship" TEXT NOT NULL,
    "nokphone" TEXT NOT NULL,
    "nokaddress" TEXT NOT NULL,
    "hypertension" TEXT NOT NULL,
    "burningsensation" TEXT NOT NULL,
    "heartdisease" TEXT NOT NULL,
    "swelling" TEXT NOT NULL,
    "sicklecellanaemia" TEXT NOT NULL,
    "chroniclowerabdominalpain" TEXT NOT NULL,
    "diabetes" TEXT NOT NULL,
    "painfulurination" TEXT NOT NULL,
    "tuberculosis" TEXT NOT NULL,
    "genitalsores" TEXT NOT NULL,
    "asthma" TEXT NOT NULL,
    "genitalgrowth" TEXT NOT NULL,
    "epilepsy" TEXT NOT NULL,
    "mentaldisorder" TEXT NOT NULL,
    "previoussurgery" TEXT NOT NULL,
    "drughistory" TEXT NOT NULL,
    "others" TEXT NOT NULL,
    "generalnotes" TEXT NOT NULL,
    "postpartum" TEXT NOT NULL,
    "hypertensionf" TEXT NOT NULL,
    "sicklecellanaemiaf" TEXT NOT NULL,
    "asthmaf" TEXT NOT NULL,
    "heartdiseasef" TEXT NOT NULL,
    "diabetesf" TEXT NOT NULL,
    "twinf" TEXT NOT NULL,
    "birthdefects" TEXT NOT NULL,
    "mentaldisorderfh" TEXT NOT NULL,
    "othersfh" TEXT NOT NULL,
    "billsbalance" TEXT[],
    "totalamountbilled" INTEGER NOT NULL,
    "totalamountpaid" INTEGER NOT NULL,
    "balanceamount" INTEGER NOT NULL,
    "recordentrydate" TIMESTAMP(3) NOT NULL,
    "registrationdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Patient_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Patient_email_key" ON "Patient"("email");
